version: '3'

networks:
  botNetwork:
    driver: bridge
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bot
    ports:
      - "8080:8080"
    networks:
      - botNetwork
  postgres:
    networks:
      - botNetwork
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: bot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
